# Generated by Django 5.0 on 2025-01-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPSave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('OTP', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'futurestar_app_otpsave',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
